" vimrc - cjonsmith
set nocompatible
filetype on
filetype plugin on
syntax on

" -- Display
set title           " Update the title of the window
set relativenumber  " Display relative line numbers
set number			" Display the current number of line cursor is on
set ruler           " Display cursor position
set wrap            " Word-wrap when too lines are too long

set scrolloff=3     " Display three lines around your cursor

" -- Filetype corrections
autocmd BufNewFile,BufRead *.ts set filetype=typescript

" -- Spaces and Tabs
set tabstop=4       " Use a tab-width of 4 characters/spaces
set shiftwidth=4    " An indent is 4 spaces wide
set softtabstop=4   " Number of spaces to use when tab is pressed

" Specific filetypes
autocmd FileType python,haskell,typescript,javascript set expandtab
autocmd FileType javascript,typescript set tabstop=2
autocmd FileType javascript,typescript set shiftwidth=2
autocmd FileType javascript,typescript set softtabstop=2

" -- Search
set ignorecase      " Ignore case when searching
set smartcase       " Ignore case if all lowercase

set incsearch       " Highlight search results while typing
set hlsearch        " Highlight other instances of searched phrase

" No beeping!
set belloff=all

" Useful backspaces
set backspace=indent,eol,start

" Hide backup file instead of abandoning
set hidden

" -- Remaps/bindings
nnoremap \ :nohls<Enter> " Turn off highlight after search with \
let mapleader = " "
nnoremap <SPACE> <Nop>
nnoremap <Leader>vrc :e ~/.vimrc<CR>
