" vimrc - cjonsmith
set nocompatible
filetype on
filetype plugin on
syntax on

" Setup pathogen
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()

" -- Display
set title           " Update the title of the window
set relativenumber  " Display relative line numbers
set number			" Display the current number of line cursor is on
set ruler           " Display cursor position
set wrap            " Word-wrap when too lines are too long

set scrolloff=3     " Display three lines around your cursor

" -- Filetype corrections
autocmd BufNewFile,BufRead *.ts set filetype=typescript

" -- Spaces and Tabs
set tabstop=4       " Use a tab-width of 4 characters/spaces
set shiftwidth=4    " An indent is 4 spaces wide
set softtabstop=4   " Number of spaces to use when tab is pressed

" Specific filetypes
autocmd FileType python,haskell,typescript,javascript set expandtab
autocmd FileType javascript,typescript set tabstop=2
autocmd FileType javascript,typescript set shiftwidth=2
autocmd FileType javascript,typescript set softtabstop=2

" -- Search
set ignorecase      " Ignore case when searching
set smartcase       " Ignore case if all lowercase

set incsearch       " Highlight search results while typing
set hlsearch        " Highlight other instances of searched phrase

" No beeping!
set belloff=all

" Useful backspaces
set backspace=indent,eol,start

" Hide backup file instead of abandoning
set hidden

" Use light version of Solarized if using GUI
if has ('gui_running')
	set background=dark
	colorscheme solarized
endif

" Fonts
if has ('gui_macvim')
	set guifont=Monaco:h13
else
	set guifont=DejaVu\ Sans\ Mono\ 11
endif

" -- Remaps/bindings
nnoremap \ :nohls<Enter> " Turn off highlight after search with \
let mapleader = " "
nnoremap <SPACE> <Nop>
nnoremap <Leader>b :ls<CR>:b<Space>
nnoremap <Leader>sb :ls<CR>:sb<Space>
nnoremap <Leader>vsb :ls<CR>:vert sb<Space>
nnoremap <Leader>l :RainbowLevelsToggle<CR>
nnoremap <Leader>a :ALEToggle<CR>
nnoremap <Leader>vrc :e ~/.vimrc<CR>
" From https://www.reddit.com/r/vim/comments/i50pce/how_to_show_commit_that_introduced_current_line/
nmap <silent><Leader>g :call setbufvar(winbufnr(popup_atcursor(split(system("git log -n 1 -L " . line(".") . ",+1:" . expand("%:p")), "\n"), { "padding": [1,1,1,1], "pos": "botleft", "wrap": 0 })), "&filetype", "git")<CR>
map <C-n> :NERDTreeToggle<CR>

" Start NERDTree automatically if opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
