abbr dotfiles 'git --git-dir=$HOME/.dotfiles/.git --work-tree=$HOME/.dotfiles'
abbr k        'kubectl'
abbr dcb      '~/Workspace/work/appcenter/dockercompose/build.ps1'
abbr dcr      '~/Workspace/work/appcenter/dockercompose/restart.ps1'
abbr dct      '~/Workspace/work/appcenter/dockercompose/tests.ps1'
abbr dcf      '~/Workspace/work/appcenter/dockercompose/functional.ps1'
abbr dcps     '~/Workspace/work/appcenter/dockercompose/ps.ps1'
abbr dcc      '~/Workspace/work/appcenter/dockercompose/clean.ps1'
abbr dcs      '~/Workspace/work/appcenter/dockercompose/stop.ps1'

# Config files
abbr cf   'cd $HOME/.config ;and ls'
abbr cff  'cd $HOME/.config/fish ;and ls'
abbr cfff 'cd $HOME/.config/fish/functions ;and ls'
abbr cfm  'cd $HOME/.xmonad ;and ls'
abbr cfv  'cd $HOME/.vim ;and ls'
abbr cfb  'cd $HOME/.vim/bundle ;and ls'

# Directory movements
abbr ws  'cd $HOME/Workspace ;and ls'
abbr bin 'cd $HOME/bin ;and ls'
abbr d   'cd $HOME/Documents ;and ls'
abbr D   'cd $HOME/Downloads ;and ls'
abbr n   'cd $NOTES_HOME ;and ls'
abbr p   'cd $HOME/Pictures ;and ls'
abbr bgs 'cd $HOME/Pictures/Backgrounds ;and ls'
abbr ac  'cd $APPCENTER ;and ls'
abbr s   'cd $HOME/Workspace/secrets ;and ls'
abbr so  'cd $HOME/Software ;and ls'