#!/usr/bin/env bash
if [ "$(uname)" = "Darwin" ]; then
    alias ls='gls --color=auto'
else
    alias ls='ls --color=auto'
    alias open='xdg-open'
fi

if command -v hostname &>/dev/null && [[ $(hostname) =~ .*\.bpdev.*\.github\.net ]]; then
  # Short for "refresh tag"
  alias rtag="aws ec2 describe-tags --filters \"Name=resource-id,Values=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)\" |\
      jq -r '.Tags[] | select(.Key == \"custom_tags\").Value'"
fi

alias cdn='cd $NOTES_HOME'
alias sourcerc='source ~/.bashrc'
alias cdw='cd ~/Workspace'
alias cdac='cd $APPCENTER'
alias k='kubectl'
alias cf='ls ~/.config && cd ~/.config'
alias ws='ls ~/Workspace && cd ~/Workspace'
alias ac='ls $APPCENTER && cd $APPCENTER'
alias d='ls $HOME/Documents && cd $HOME/Documents'
alias D='ls $HOME/Downloads && cd $HOME/Downloads'
alias b='ls $HOME/bin && cd $HOME/bin'
alias s='ls $HOME/Workspace/secrets && cd $HOME/Workspace/secrets'
alias brc='$EDITOR $HOME/.bashrc'

command -v ruby >/dev/null 2>&1 && \
    alias inflate='ruby -r zlib -e "puts Zlib::Inflate.inflate(STDIN.read)"'
